name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - uses: actions/upload-artifact@v2
        with:
          name: with-modules
          path: ./
  es-lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: with-modules
          path: ./
      - name: Проверка линтером JS
        run: npx eslint 'src/scripts/**/*.js'
  stylelint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/download-artifact@v2
        with:
          name: mwith-modules
          path: ./
      - name: Проверка линтером CSS
        run: npx stylelint 'src/styles/**/*.css'
