name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Проверка линтером JS
        run: npx eslint 'src/scripts/**/*.js'
  stylelint:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка необходимых зависимостей
        run:  npm install --save-dev stylelint-config-standard
      - name: Проверка линтером CSS
        run: npx stylelint 'src/styles/**/*.css'
