name: Netlify Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - name: Загрузка контента
        uses: actions/checkout@v2
        with:
          repository: Y-Doka/content
          path: content
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - name: Сборка сайта
        run: |
          node make-links.js --default
          npm run build
      - name: Публикация сайта
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --message='Публикация платформы (https://github.com/doka-guide/platform/commit/${{ github.sha }})' --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
