name: Social Cards

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - name: Загрузка контента
        uses: actions/checkout@v2
        with:
          repository: doka-guide/content
          path: content
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - name: Сборка сайта
        run: |
          node make-links.js --default
          npm run build
          npm install --global screenshoteer
          OIFS=$IFS; IFS=$'\n'; files=($(ls dist/*/*/index.og.html)); IFS=$OIFS
          for in_file in $files; do
            tmp_file=$(echo "${in_file}.t")
            while read a; do
              echo ${a//\/styles/\.\./\.\./styles}
            done < $in_file > $tmp_file
            mv $tmp_file $in_file
            input_file='file:///home/runner/work/platform/platform/${in_file}'
            output_og='${file//\index.og.html/images/covers/og.png}'
            output_twitter='${file//\index.og.html/images/covers/twitter.png}'
            screenshoteer --w 1024 --h 512 --url $input_file --file $output_og
            screenshoteer --w 1024 --h 512 --url $input_file --file $output_twitter
            rm $og_file
          done
      - name: Публикация сайта
        id: surge
        continue-on-error: true
        run: |
          if ! [[ ${{ env.SURGE_TOKEN == '' }} ]]; then
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token ${{ env.SURGE_TOKEN }}
          else
            echo 'Публикация для форка репозитория'
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token '6973bdb764f0d5fd07c910de27e2d7d0'
          fi
          echo 'Ссылка на превью — ${{ env.DEPLOY_DOMAIN }}'
