name: Social Cards

on:
  pull_request:

jobs:
  social:
    runs-on: ubuntu-latest
    env:
      DEPLOY_DOMAIN: 'https://${{ github.repository_owner }}-platform-pr-${{ github.event.number }}.surge.sh'
      SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
    steps:
      - name: Загрузка платформы
        uses: actions/checkout@v2
      - name: Загрузка контента
        uses: actions/checkout@v2
        with:
          repository: doka-guide/content
          path: content
      - name: Кэширование модулей
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Установка модулей
        run: npm ci
      - name: Сборка сайта
        run: |
          node make-links.js --default
          npm run build
          npm install --global screenshoteer
          base_path="/Users/igorkorovchenko/Projects/doka-platform/"
          files=( $(ls dist/*/*/index.og.html) )
          for in_file in ${files[@]}; do
            tmp=""
            tmp_file="${base_path}${in_file}.t"
            touch $tmp_file
            while IFS= read -r line; do
              line="${line//\/styles/../../styles}"
              tmp="${tmp}${line}\n"
            done <<< $(cat $in_file)
            echo $tmp > $tmp_file
            mv $tmp_file $in_file
            input_file="file://${base_path}${in_file}"
            covers="${in_file//index.og.html/images/covers/}"
            mkdir -p $covers
            screenshoteer --w 1200 --h 630 --url $input_file --file "${covers}og.png"
            screenshoteer --w 1024 --h 1024 --url $input_file --file "${covers}twitter.png"
            rm $in_file
          done
      - name: Публикация сайта
        id: surge
        continue-on-error: true
        run: |
          if ! [[ ${{ env.SURGE_TOKEN == '' }} ]]; then
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token ${{ env.SURGE_TOKEN }}
          else
            echo 'Публикация для форка репозитория'
            npx surge ./dist ${{ env.DEPLOY_DOMAIN }} --token '6973bdb764f0d5fd07c910de27e2d7d0'
          fi
          echo 'Ссылка на превью — ${{ env.DEPLOY_DOMAIN }}'
